
## motivated-quartz
creation date: 2025-10-14


### Description and Rationale

I am a final-year Computer Engineering students, future civil aviation professionals. I decided to participate in the China Data Challenge because it aligns perfectly with our interests in data science, aviation analytics, and sustainability. Through my studies, i have worked on projects involving time-series forecasting models, predictive modeling, and machine learning, which have equipped us with strong analytical and teamwork skills. We see this challenge as an opportunity to apply our knowledge to real-world aviation problems, learn from the open data community, and contribute to enhancing the transparency and efficiency of the aviation industry through data-driven insights.

### Details

* Type: Independent
* Country: China

```{r echo=FALSE}
library(gt)

gt(tibble::tribble(
  ~id, ~forename, ~surname,                                                    ~affiliation,
   1L,      "墨诗",      "王", "北京航空航天大学 (Beijing University of Aeronautics and Astronautics)"
  )
)
```
