---
title: "Ranking"
format:
  html:
    toc: false
acronyms:
  insert_loa: false
---

## Leaderboard

::: {.callout-warning title="Attention"}
We will post URGENT/IMPORTANT news here but better to follow things up on \
[OSN's Discord {{< fa brands discord >}} channel `#prc-data-competition`][prc-discord]  
(if not already done, you need to access [OSN Discord server](https://discord.gg/RPh89jpVVz) first)
:::



```{=html}
<iframe width="100%" height="800" frameborder="0"
  src="https://observablehq.com/embed/@espinielli/dc25-leaderboard@593?cells=leaderboard"></iframe>
```


All paged submissions rankings can be retrieved via the REST API at the [full leaderboard JSON][leaderboard] (use the value of `nextCursor` in the `cursor=` parameter in the URL query).

There are other endpoints, you can have a look [here][api]

[api]: <https://datacomp.opensky-network.org/api/swagger-ui/>
[leaderboard]: <https://datacomp.opensky-network.org/api/competitions/71c49292-6139-425f-803a-52ee8730ba58/leaderboard?limit=100&cursor=>


## Criteria for Ranking Submissions

Ranking will be based on the best RMSE of a team's submissions.


There will be two phases for submissions:

1. phase 1: till **2025-11-09T23:59:59Z** \
   Ranking will be based on `fuel_rank_submission.parquet`
1. phase 2: from **2025-11-10T00:00:00Z** till **2025-11-30T23:59:59Z** \
   Ranking will still be based on `fuel_rank_submission.parquet` BUT
   the submission for eligibility to final prize will be based on
   `fuel_final_submission.parquet` [^note]. For the **additional** flight list
   and flight trajectories for phase 2/final phase see 
   `flightlist_final.parquet` and
   `flights_final/<flight_id>.parquet`.  
   Final submission files are being validated, see 
   [the submission section](submission.qmd#phase2) for more details.

[^note]: This is to avoid the possibility of _leaning_ from the leaderboard
         results.

::: {.callout-note title="Attention"}
The ranking datasets are now available for download in the buckets.  
:::



### Eligibility for Prize {#eligibility}

The winning submissions/solutions will only be eligible for the awards if

* all source code and additional data sets used will be made openly available
  to be published under the **GNU GPLv3 license** on the Challenge github
  account.
* use of external dataset is permitted if open data and documented.
* sufficient documentation is provided to understand and reproduce the results.
* the solution is _original_: teams must use their own original solutions.
  Re-using any existing implementation is only allowed if the original authors 
  grant you the rights to use their solution and if you made significant
  modifications to the algorithm or model.
  In particular, simply re-using existing code and rewriting the data input and 
  output mechanism is not sufficient. Adding parameters to the model and 
  modifying filters to match the specific peculiarities of the data, however,
  can be considered sufficient. 


### Final Prize 

We reserved a total of 5000 EUR for the first 3 ranking teams.

The Selection Committee will review and discuss the top ranking teams and
select final Awardees considering

1. their final ranking score,
1. the originality of the proposed model
1. the open availability of the code and the relevant documentation provided.

By participating in the Challenge, you agree to be bound by the final decision
of the PRC Data Challenge selection committee. 



[prc-discord]: <https://discord.com/channels/1252625490930307142/1304403918515605504> "Discord channel for PRC Data Challenge"