---
title: "Submission"
format:
  html:
    toc: false
acronyms:
  insert_loa: false
---

We provide a submission file for each phase of the Challenge,
`fuel_rank_submission.parquet` for phase 1 and
`fuel_final_submission.parquet` for phase 2.

For phase 1 there are companion trajectories and flight list.

Each team will have to submit its predictions in its own bucket, with a
file name template as follows

> `<team-name>_v<incremental integer>.parquet`  

The `fuel_rank_submission.parquet` (`fuel_final_submission.parquet`) payload
looks something like

```
idx     flight_id                start                  end  fuel_kg
  0  prc770822360  2025-04-13 04:31:04  2025-04-13 05:01:04      0.0
  1  prc770822360  2025-04-13 05:01:04  2025-04-13 05:16:04      0.0
  2  prc770822360  2025-04-13 05:16:04  2025-04-13 05:46:04      0.0
  3  prc770822360  2025-04-13 05:46:04  2025-04-13 06:01:04      0.0
...
```

### Submission format {#phase1}

You should submit a **parquet** file, named
`<team-name>_v<incremental integer>.parquet`, with your predictions
with exactly all entries as in in `fuel_rank_submission.parquet`
(`fuel_final_submission.parquet`), i.e. something with a payload like:

```
idx     flight_id                start                  end  fuel_kg
  0  prc770822360  2025-04-13 04:31:04  2025-04-13 05:01:04    250.3 
  1  prc770822360  2025-04-13 05:01:04  2025-04-13 05:16:04    120.8
  2  prc770822360  2025-04-13 05:16:04  2025-04-13 05:46:04   2500 
  3  prc770822360  2025-04-13 05:46:04  2025-04-13 06:01:04   1300.9 
...
```

We require each row to match `idx`, `flight_id`, `start` and `end` before
`fuel_kg` will be considered by the ranking script when calculating the RMSE.
Errors will be issued in case of mismatch.
Errors will also be issued in case of missing or extra rows.



### Submission for phase 2/final phase{#phase2}

During phase 2/final phase you can continue to submit predictions with filenames
`<team-name>_v<incremental integer>.parquet`
like in phase 1: based on `fuel_rank_submission.parquet`.

For the eligibility for final prize you should upload your (best) prediction
in a file named 

`<team-name>_final.parquet`

The rows in this file are like the ones in `fuel_final_submission.parquet`
which includes the intervals of phase 1 (24289 for 1888 distinct flights)
and additional ones for the final phase (37456 for 2836 distinct flights).
Total rows is 61745.

::: {.callout-important title="VALIDATION"}

You can overwrite your `<team-name>_final.parquet` and each time it will be
validated with checks like for phase 1, namely
missing predictions, NaN, rows match on icao24,...  
Feed back is written back to the bucket with the same logic as for phase 1.

:::
